project:
  type: website
  output-dir: docs

website:
  title: "Hirayama Nanami"
  navbar:
    left:
      - post.qmd
      - project.qmd

format:
  html:
    code-tools: true
    theme: sandstone
    css: styles.css
    toc: true
  # revealjs:
  #   slide-number: true
  #   toc: true
  #   transition: fade
  #   theme: black



