project:
  type: website
  output-dir: docs

website:
  title: "Hirayama Nanami"
  navbar:
    left:
      - post.qmd
      - project.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



