project:
  type: website
  output-dir: docs

website:
  title: "Hirayama Nanami"
  navbar:
    left:
      - post.qmd
      - project.qmd

format:
  html:
    code-tools: true
    theme: sandstone
    css: styles.css
    # javascript: script.js
    toc: true
    grid:
      margin-width: 450px
    
  # revealjs:
  #   slide-number: true
  #   toc: true
  #   transition: fade
    # theme: beige

# filters:
#   - whitphx/stlite


# 気になるテーマ集！
# zephyr
# united
# spacelab
# simplex
# pulse
# materia
# lumen
# litera
# journal
# flatly