project:
  type: website
  output-dir: docs

website:
  title: "Hirayama Nanami"
  navbar:
    left:
      - posts.qmd
      - free.qmd

format:
  html:
    code-tools: true
    theme: sandstone
    css: styles.css
    lang: ja
    toc: true
    # grid:
    #   margin-width: 450px
  # typst:
  #   mainfont: "Noto Sans JP"
    
  # revealjs:
  #   slide-number: true
  #   toc: true
  #   transition: fade
    # theme: beige

# filters:
#   - whitphx/stlite


# 気になるテーマ集！
# zephyr
# united
# spacelab
# simplex
# pulse
# materia
# lumen
# litera
# journal
# flatly