---
title: "「データ解析のための数理統計入門」第1章 演習問題 解答"
format: html
code-fold: true
date: 2024/06/28
toc: true
lang: ja
categories:
  - 統計
  - データ解析のための数理統計入門
status: "作成中"
---

## １問目

### 問題
大学生の就職活動に関して、ある企業にエントリーした学生は男性が60%を占めていたが、採用を内定された割合は、男性は男性応募者の40%、女性は女性応募者の30%であった。


<div class="extra-space1"></div>

⑴この企業の男女合わせた全体の応募者に対する男性の採用内定率、女性の採用内定率を求めよ。

⑵この企業の男女合わせた全体の採用内定率を求めよ。

⑶この企業の採用内定者の名簿から一人をランダムに選んだ場合、それが女性である確率を求めよ。

<div class="extra-space2"></div>

### 解答
#### ⑴

ある企業にエントリーした学生全体を$\Omega$とし、男性である事象を$A$とする。また男性である確率は$P(A)$と表します。

この場合女性である事象は$A^c$で表され、女性である確率は$P(A)$となります。

男性の割合は60%なので、$P(A)=0.6$である。
女性の割合は、$P(A^c)=1-0.6=0.4$である。

<div class="extra-space2"></div>

また採用される事象は$B$と表し、採用されない事象は$B^c$となります。

男性は男性応募者の40%、女性は女性応募者の30%が採用内定である。これは条件付き確率で表される。40%とは、男性である条件のもとで採用した確率なので、$P(B|A)=0.4$。同様に、$P(B|A^c)=0.3$

<div class="extra-space2"></div>

⑴で聞かれているのは、男性の採用内定率つまり$P(A \cap B)$と、女性の採用内定率つまり$P(A^c \cap B)$である。

<div class="extra-space2"></div>

$P(A \cap B)=P(B|A) \times P(A) = 0.4 \times  0.6 = 0.24$

$P(A^c \cap B)=P(B|A^c) \times P(A^c) = 0.3 \times  0.4 = 0.12$

<div class="extra-space2"></div>

#### ⑵

⑵で聞かれているのは、全体の採用内定率つまり$P(B)$である。

$A+A^c=\Omega$で、$A$と$A^c$は排反より、全確率の公式を用いると、以下の式が成り立つ。

$P(B) = P(B|A) \times P(A) + P(B|A^c) \times P(A^c) = 0.24+0.12=0.36$

<div class="extra-space2"></div>

#### ⑶

⑶は条件付き確率の問題で、採用内定者のもとで女性である確率つまり$P(A^c|B)$である。

$P(A^c|B)=\frac{P(A^c \cap B)}{P(B)}= \frac{0.12}{0.36} =\frac{1}{3}$ 

<div class="extra-space3"></div>

## 2問目

### 問題

週の天気予報によると、土曜日に雨の降る確率は25%、日曜日に雨の降る確率も25%である。
週末の土日のどこかに雨が降る確率は25+25=50%になると考えた。これは正しいかどうか。

### 解答

正しくない。

土曜日に雨が降る事象を$A$とし、確率は$P(A)$で表される。

日曜日に雨が降る事象を$B$とし、確率は$P(B)$で表される。

<div class="extra-space2"></div>

この問題が言っていることは$P(A \cup B) = P(A)+P(B)$になるということである。しかし、これが成り立つのは、$A$と$B$が排反の時である。

事象$A$と$B$はどう考えても排反ではないので、成り立たない。

:::{.callout-note}
事象$A$と$B$が排反とは、$A$と$B$が同時に起こり得ないということです。
:::

$P(A \cup B) = P(A)+P(B)-P(A \cap B)$なので、確率は50%より低くなることが考えられる。

## 3問目

### 問題

ある大学のある学部はA学科とB学科の２つからなり、それぞれの志願者数と合格率が男女別に次の表で与えられたとする。学部全体の男女の合格率に関して、シンプソンのパラドクスが生ずるような$a$の条件を考えよ。

::: {layout-ncol=2}
| A 学科 | 志願者 | 合格率 |
|------|------|------|
| 男性    | 500    | 60%    |
| 女性    | 30    | 70%   |


| B 学科 | 志願者 | 合格率 |
|------|------|------|
| 男性    | 400    | 10%    |
| 女性    | 300    | a%   |


:::

### 解答

A学科を見ると女性の方が合格率が高い。

男女の合格率に関してシンプソンのパラドクスが生じるようにという問題です。つまり、B学科もA学科同様に学科単体では女性の合格率が高いが、A学科とB学科を合計すると男性の合格率のほうが高くなるような$a$を求める問題です。

<div class="extra-space2"></div>

まず、学科単体では女性の合格率が高くなるので、$a>10$です。

<div class="extra-space2"></div>

次に、男女別の学科合計の合格率を考えます。

**男性の合格率**

$\frac{500 \times 0.6 + 400 \times 0.1}{500+400}=\frac{340}{900}$

**女性の合格率**

$\frac{30 \times 0.7 + 300 \times a/100}{500+400} = \frac{21+3a}{330}$

男性の合格率>女性の合格率となればいいので、以下の式が成り立ちます。

$\frac{340}{900}>\frac{21+3a}{330}$

$a < \frac{340}{900} \times 110 -7\fallingdotseq 34.6$ 


よって$a$の条件とは $10<a<34.6$ である。


## 4問目

### 問題

両親と二人の子供がいる4人家族において、同じ誕生日の人がいる確率を求めよ。

### 解答

誕生日問題は補集合で考えるとわかりやすい。

同じ誕生日の人が**いない**事象を$A$とすると、求めたい事象は$A^c$であり、求めたい確率は$P(A^c)$である。

$P(A)=\frac{365}{365} \cdot \frac{364}{365} \cdot \frac{363}{365} \cdot \frac{362}{365} = \frac{364\cdot 363\cdot 362}{365^3}$

$P(A^c)=1-P(A)=1-\frac{364\cdot 363\cdot 362}{365^3} = 0.016$

よって約1.6%である。


## 5問目

[ここ](/posts/seminor2024_0611/)に書いてあるので、省略します。

## 6問目

### 問題
条件付き確率について不等式$P(A|D) \geq P(B|D)$,$P(A|D^c) \geq P(B|D^c)$が成り立つならば、$P(A) \geq P(B)$であることを示せ。

### 解答

$P(A|D^c)$のような補集合の条件付き確率が出てきていることから、全確率の公式を用いることが推察できます。

$P(A|D)P(D) + P(A|D^c)P(D^c) =P(A)$

$P(B|D)P(D) + P(B|D^c)P(D^c) =P(B)$

この２つを用いれば解くことができそうですね。

<div class="extra-space2"></div>

$P(A|D) \geq P(B|D)$の両辺に$P(D)$をかけても不等式は成り立ちます。

$P(A|D)P(D) \geq P(B|D)P(D)$

$P(A|D^c) \geq P(B|D^c)$の両辺に$P(D^c)$をかけても不等式は成り立ちます。

$P(A|D^c)P(D^c) \geq P(B|D^c)P(D^c)$

不等式同士を辺々足しても大小関係は変わらないため、以下の式が成り立つ。

$P(A|D)P(D)+P(A|D^c)P(D^c) \geq P(B|D)P(D)+ P(B|D^c)P(D^c)$

全確率の公式より

$P(A) \geq P(B)$である。


## 7問目

### 問題

次の多項式の係数を求めよ。

⑴$(x+y)^6$における$x^3y^3$の係数

⑵$(x+y+z)^6$における$x^2y^2z^2$の係数

### 解答

⑴

$\begin{pmatrix}
6 \\
3 
\end{pmatrix} =\frac{6!}{3!3!}=20$

⑵

$\begin{pmatrix}
& 6 & \\
2 & 2 & 2
\end{pmatrix} =\frac{6!}{2!2!2!}=90$

## 8問目

### 問題
正しいコインを３回投げる時次の確率を求めよ

⑴少なくとも１回は表が出るという条件のもとで２回以上表の出る確率

⑵少なくとも１回は裏が出るという条件のもとで２回以上表の出る確率

### 解答
正しいコインの意味はおそらく裏表が1/2の確率になるという意味だと思います。

⑴

条件付き確率ですね。

少なくとも１回は表が出るという事象を$A$として、2回以上表が出る事象を$B$とする。

求めるのは$P(B|A)$である。

<div class="extra-space2"></div>

$P(B|A)=\frac{P(A \cap B)}{P(A)}$となるので、それぞれの確率を求めれば良い。

<div class="extra-space2"></div>

$P(A)$は余事象ですぐ求めることができる。

$P(A)=1-P(A^c)=1-(\frac{1}{2})^3=\frac{7}{8}$

<div class="extra-space2"></div>

$P(A \cap B)$ は$B \subset A$より$P(A \cap B)=P(B)$である。
また、表が２回出る確率は${}_3 C_1(\frac{1}{2})^3$です。

$P(A \cap B)=P(B)=\frac{1}{8}+\frac{3}{8}=\frac{1}{2}$

<div class="extra-space2"></div>

よって、

$P(B|A)=\frac{P(A \cap B)}{P(A)}= \frac{P(1/2)}{7/8}=\frac{4}{7}$

⑵

⑴と同様に求めます。

少なくとも１回は裏が出るという事象を$A$として、2回以上表が出る事象を$B$とする。

$P(A)=1-P(A^c)=1-(\frac{1}{2})^3=\frac{7}{8}$

少なくとも１回は裏が出るかつ２回以上表が出る事象は、表が２回（裏が１回）の事象のみである。

$P(A \cap B)={}_3 C_1(\frac{1}{2})^3=\frac{3}{8}$

よって、

$P(B|A)=\frac{P(A \cap B)}{P(A)}= \frac{P(3/8)}{7/8}=\frac{3}{7}$

## 9問目

### 問題
2人の子供がいる夫婦について、第一子が女の子であるという条件のもとで二人とも女の子であるという確率を求めよ。また子供の一人が女子であるという条件のもとで二人とも女子である確率を求めよ。

### 解答

これも条件付き確率の問題と考えることができます。

1つ目について。

A：第一子が女の子である

B：二人とも女の子である

一つ目で求められているのは$P(B|A)$である。

$P(A)=1/2$

$P(A \cap B)=1/2 \times 1/2 =1/4$

$P(B|A)= \frac{1/4}{1/2} = 1/2$

2つ目について。

C：子供の一人が女子である

D：二人とも女子である

$P(C)=1- (\frac{1}{2})^2 = 3/4$

$P(D \cap C)=1/4$

$P(D|C)= \frac{1/4}{3/4} = 1/3$

## 10問目

### 問題
独立性に関して次の問いに答えよ
⑴