---
title: "6月18日「データ解析のための数理統計入門」第2章 2.1.6ポアソン分布"
format: html
code-fold: true
date: 2024/06/18
toc: true
lang: ja
categories:
  - データ解析のための数理統計入門
  - python
status: "完了"
---

## ポアソン分布とは

まれな現象が起こる回数を$X$とするとき、確率関数が以下の関数である分布を\textbf{ポアソン分布}という。$Po(\lambda)$ で表す。
$$p(k) = P(X=k) = \frac{\lambda^k}{k!}e^{-\lambda}, k = 0,1,2,3, \ldots$$

$\lambda$は生起率（強度）と呼ばれるパラメーターであり、単位時間あたりに起こる回数である。
$e$ は自然対数の底である。

## ポアソン分布のグラフ

```{python}
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import poisson
import japanize_matplotlib

# 複数のλ値を定義
lambdas = [1, 1.3, 3, 5, 5.6, 7, 9]

# x の範囲を定義
x = np.arange(0, 20)

# グラフのプロット
plt.figure(figsize=(10, 6))

for lambda_ in lambdas:
    pmf = poisson.pmf(x, lambda_)
    plt.plot(x, pmf, marker='o', linestyle='-', label=f'λ = {lambda_}')

# x軸の目盛りを整数に設定
plt.xticks(np.arange(0, 21, 1))

plt.xlabel('x')
plt.ylabel('確率')
plt.title('λを変動させたポアソン分布')
plt.legend()
plt.grid(True)
plt.savefig('1.png')
plt.show()
```

### $\lambda$ が正の整数のとき

```{python}
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import poisson
import japanize_matplotlib

# 複数のλ値を定義
lambdas = [1, 3, 5, 7, 9]

# x の範囲を定義
x = np.arange(0, 20)

# グラフのプロット
plt.figure(figsize=(10, 6))

for lambda_ in lambdas:
    pmf = poisson.pmf(x, lambda_)
    plt.plot(x, pmf, marker='o', linestyle='-', label=f'λ = {lambda_}')

# x軸の目盛りを整数に設定
plt.xticks(np.arange(0, 21, 1))

plt.xlabel('x')
plt.ylabel('確率')
plt.title('λを変動させたポアソン分布')
plt.legend()
plt.grid(True)
plt.savefig('1.png')
plt.show()
```

### $\lambda$ が正の実数かつ整数ではない時

```{python}
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import poisson
import japanize_matplotlib

# 複数のλ値を定義
lambdas = [1.3, 3.6, 5.9, 7.32, 9.333]

# x の範囲を定義
x = np.arange(0, 20)

# グラフのプロット
plt.figure(figsize=(10, 6))

for lambda_ in lambdas:
    pmf = poisson.pmf(x, lambda_)
    plt.plot(x, pmf, marker='o', linestyle='-', label=f'λ = {lambda_}')

# x軸の目盛りを整数に設定
plt.xticks(np.arange(0, 21, 1))

plt.xlabel('x')
plt.ylabel('確率')
plt.title('λを変動させたポアソン分布')
plt.legend()
plt.grid(True)
plt.savefig('1.png')
plt.show()
```

#### グラフからわかること

1. $\lambda$ が正の整数のもとで,$P(\lambda)=P(\lambda-1)$であることがわかる。


\begin{align*}
    P(\lambda) &= \frac{\lambda^\lambda}{\lambda!} e^{-\lambda} \\
    P(\lambda-1) &= \frac{\lambda^{\lambda-1}}{(\lambda-1)!} e^{-\lambda}
\end{align*}
$P(\lambda-1)$ の分母分子に$\lambda$ をかけると、$P(\lambda)$ と同じ式になるため,$P(\lambda)=P(\lambda-1)$

2. $\lambda$ が正の整数のもとで,$P(\lambda)=P(\lambda-1)$が最頻値であることがわかる。
3. $\lambda$ が正の実数かつ整数ではないときのもとで,$P([\lambda])$が最頻値であることがわかる。

2と3は演習問題に続く.

## ポアソン分布の具体例
1. ある都市の１日に起こる交通事故の数
2. ある都市で１年間のうちに肺がんで死ぬ数

確率が極端に少なそうな事柄がポアソン分布を用いることが多い。

## ポアソン分布が確率関数である証明

テーラー展開

\begin{align*}
    e^\lambda &= 1 + x + x^2/ 2! + x^3/ 3! \ldots \\
    &= \sum_{k=0}^\infty \frac{x^k}{k!}
\end{align*}

\begin{align*}
    \sum_{k=0}^\infty p(k) &= \sum_{k=0}^\infty \frac{\lambda^k}{k!} e^{-\lambda} = e^{\lambda}e^{-\lambda} = 1
\end{align*}
$\sum_{k=0}^\infty p(k)$が1であるため、$\frac{\lambda^k}{k!} e^{-\lambda}$ が確率関数であることがわかる. 

## 命題2.6

**命題2.6** ポアソン分布$Po(\lambda)$に従う確率変数をXとすると、Xの平均と分散はともに$\lambda$である。

**$E[X]$について**

$\sum^\infty_{k=0}\frac{\lambda^k}{k!} = e^\lambda$について両辺を微分します。

\begin{equation*}
    \frac{d}{d\lambda}(e^\lambda)  = e^\lambda
\end{equation*}
\begin{align*}
    \frac{d}{d\lambda}(\sum^\infty_{k=0}\frac{\lambda^k}{k!}) &= \sum^\infty_{k=0}\frac{k\lambda^{k-1}}{k!} 
    = \sum^\infty_{k=1}\frac{k\lambda^{k-1}}{k!} 
\end{align*}
両辺に$\lambda e^{-\lambda}$をかけます。
\begin{equation*}
    e^\lambda \lambda e^{-\lambda} = \lambda
\end{equation*}
\begin{equation*}
    \sum^\infty_{k=1}\frac{k\lambda^{k-1}}{k!} \lambda e^{-\lambda} = \sum^\infty_{k=1}\frac{k\lambda^{k}}{k!} e^{-\lambda} = E[X]
\end{equation*}

**$Var[X]$**について

同様に求められた式を微分します。
  \begin{equation*}
    \sum_{k=1}^{\infty} k(k-1)\frac{\lambda^{k-2}}{k!} = e^\lambda
  \end{equation*}

  両辺に$\lambda^2 e^{-\lambda}$ をかけます
  \begin{equation*}
    \sum_{k=1}^{\infty} k(k-1)\frac{\lambda^{k}}{k!} e^{-\lambda} = \lambda^2
  \end{equation*}

  \begin{equation*}
    Var(X) = E[X(X-1)] + E[X]-(E[X])^2 = \lambda^2 +\lambda -\lambda^2 = \lambda
  \end{equation*}


## 命題2.7 二項分布のポアソン近似
$np=\lambda$ が一定のもとで、$p \rightarrow 0$,$n \rightarrow \infty$とすると、二項分布$Bin(n,p)$ はポアソン分布$Po(\lambda)$ に収束する。

### 命題2.7の証明

\begin{align*}
    \lim_{n \rightarrow \infty} {}_n \mathrm{C}_k p^k (1-p)^{n-k} &= \lim_{n \rightarrow \infty} \frac{n!}{(n-k)!k!} \left(\frac{\lambda}{n}\right)^k \left(1-\frac{\lambda}{n}\right)^{n-k} \\
    &= \lim_{n \rightarrow \infty} \frac{\lambda^k}{k!} \frac{n!}{(n-k)!n^k} \left(1-\frac{\lambda}{n}\right)^n \left(1-\frac{\lambda}{n}\right)^{-k} \\
    &= (\frac{k!}{\lambda^k}) e^{-\lambda}
\end{align*}

$n\rightarrow \infty$のとき、$\frac{n!}{(n-k)!n^k}\rightarrow 1, (1-\frac{\lambda}{n})^n \rightarrow e^{-\lambda},(1-\frac{\lambda}{n})^{-k} \rightarrow 1$より。