---
title: "KaggleのJapanese Universityを使ってデータ分析"
description: "大学の分布とかを可視化してみたい！"
date: "2024-06-23"
categories:
  - Kaggle
  - Analize
  - Dataset
---
# データセット（Kaggleより）

https://www.kaggle.com/datasets/webdevbadger/japanese-universities

# データの外観を眺める

```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
```


```{python}
data = pd.read_csv("./data/japanese_universities.csv")
```

```{python}
data.head(1)
```

```{python}
data.columns
```

<div class="extra-space"></div>
<div class="extra-space"></div>
<div class="extra-space"></div>

1つ目の列がUnnamed: 0になっているので、IDに変えておく。

列名を変える方法を知らなかったけど、renameというメソッドがあるっぽい。（[https://qiita.com/kizataka/items/4d44a3dc8f32f9ca2c59](https://qiita.com/kizataka/items/4d44a3dc8f32f9ca2c59)）


```{python}
data = data.rename(columns={'Unnamed: 0': 'ID'})

data.head(3)
```

```{python}
data.info()
```

```{python}
data.describe()
```

## 列の意味

| **コード**            | **説明**                                                                       |
|----------------------|---------------------------------------------------------------------------------|
| **code**             | 文部科学省が割り当てた識別コード                                                |
| **name**             | 大学名の公式英訳                                                                 |
| **name_jp**          | 大学名の公式日本語名                                                             |
| **type**             | 大学の種類（国立、公立、私立のいずれか）                                         |
| **type_jp**          | 大学の種類（日本語）                                                             |
| **address**          | 大学の住所                                                                       |
| **postal_code**      | 郵便番号                                                                         |
| **phone**            | 電話番号                                                                         |
| **state_code**       | 都道府県に関連付けられたコード                                                   |
| **state_jp**         | 都道府県                                                                         |
| **latitude**         | 大学の位置の緯度                                                                 |
| **longitude**        | 大学の位置の経度                                                                 |
| **found**            | 大学の設立年月                                                                   |
| **faculty_count**    | 大学の学部数                                                                     |
| **department_count** | 大学の学科数                                                                     |
| **has_grad**         | 大学院の有無（True または False）                                               |
| **has_remote**       | 遠隔教育の有無（True または False）                                             |
| **review_rating**    | 大学のレビュー評価                                                               |
| **review_count**     | 大学のレビュー数                                                                 |
| **difficulty_SD**    | 大学の難易度の標準偏差                                                          |
| **difficulty_rank**  | 大学の難易度ランク（最高から最低のランク順は - [S, A, B, C, D, E, F]）         |

## 欠損値
```{python}
data.isnull().sum()
```

どうやらちょくちょくあるっぽい。

# 様々な疑問を可視化していく！
## 1.国立・公立・私立の数ってどれくらい違うの？

### 予想
1. 私立の数が一番多い
2. 国立は１都道府県１つくらい？
3. 公立は国立よりは多く私立よりは少ない

### 結果
```{python}
data.type_jp.value_counts()
```

1. 私立の数が一番多い　→　◯
2. 国立は１都道府県１つくらい？　→　×　（１都道府県2つくらいあるっぽい）
3. 公立は国立よりは多く私立よりは少ない　→　◯

#### 棒グラフ
https://plotly.com/python/histograms/

```{python}
fig1 = px.histogram(data, x="type_jp")
fig1.show()
```


#### 円グラフ

https://plotly.com/python/pie-charts/

```{python}
fig2 = px.pie(data,  names='type_jp')
fig2.show()
```

## 2.各都道県の国立・公立・私立の分布を知りたい！
### 予想
1. 首都圏は私立が多いイメージがある
2. 都会（大阪・名古屋・福岡）などは首都圏と同様に私立が多い
3. 国立はだいたい平等に各都道府県にある
4. 公立+国立が平等になるようにできてるかも！補填し合うみたいなイメージで
5. 予想ではないけど、大学数の合計の違いも気になるかも。東京は大学多そう
