---
title: "「データ解析のための数理統計入門」第2章 演習問題 解答"
format: html
code-fold: true
date: last-modified
toc: true
lang: ja
categories:
  - 統計
  - データ解析のための数理統計入門
status: "作成中"
---

# 問1

## 問題
二項分布$Bin(n,p)$の確率関数を$p_k=P(X=k)$,$k=0, \ldots, n$とする。

⑴$p_k$を$p_{k-1}$を用いて表せ。$\{p_0,\ldots,p_n\}$の中で最大を与える$k$を求めよ

⑵$p=1/2$のとき、$n=10,k=9$の時の確率と$n=20,k=18$の時の確率ではどちらが大きいか。


## 解答

::: {#nte-one .callout-note}
確率変数$X$が二項分布$Bin(n,p)$に従う時、$X=k$となる確率は$q=1-p$に対して次のようになる。

$$
p(k)=\binom{n}{k}p^k q^{n-k}
$$

:::

### ⑴

$p_k=\binom{n}{k}p^k q^{n-k}$と$p_{k-1}=\binom{n}{k-1}p^{k-1} q^{n-(k-1)}$の関係を示したいです。

カッコのままだとわかりにくかったので、階乗に直します。

$p_k=\frac{n!}{k!(n-k)!} p^k q^{n-k}$ を　$p_{k-1}=\frac{n!}{(k-1)!(n-(k-1))!} p^{k-1} q^{n-(k-1)}$の関係を示す問題です。

式変形していきます。

\begin{align}
p_{k}
&=
\binom{n}{k}p^k q^{n-k} 
\\

&=
\frac{n!}{k!(n-k)!} p^k q^{n-k} 
\\

&=
\frac{n!(n-(k-1))}{k(k-1)! \cdot (n-(k-1))!} p^k q^{n-k} 
\\

&=
\frac{n!(n-(k-1))}{k(k-1)! \cdot (n-(k-1))!} p^{k-1} q^{n-(k-1)} \frac{p}{q}
\\

&=
\frac{n!}{(k-1)!(n-(k-1))!} p^{k-1} q^{n-(k-1)}\frac{p(n-(k-1))}{kq}
\\
&=
\frac{p(n-(k-1))}{kq} p_{k-1} 
\\
&=
\frac{p(n-(k-1))}{k(1-p)} p_{k-1} 

\end{align}

きれいに治すと、
$$
p_k=\frac{p}{1-p} \frac{n-(k-1)}{k} p_{k-1} 
$${#eq-one}

となります。

$\{p_0,\ldots,p_n\}$の中で最大を与える$k$を求める問題です。$p_k \ge p_{k-1}$かつ$p_k \ge p_{k+1}$となるような$k$の確率が最大となります。@eq-one が誘導になってることがわかりますね。


$$
p_k = \frac{p}{1-p} \frac{n-(k-1)}{k} p_{k-1} \ge p_{k-1}
$$

かつ

$$
p_{k+1} = \frac{p}{1-p} \frac{n-k}{k+1} p_{k} \le p_{k}
$$

が成り立つことである。

1つ目の式は確率は0以上であるため、下のように変形できる。

\begin{align}
p_k = \frac{p}{1-p} \frac{n-(k-1)}{k} p_{k-1} &\ge p_{k-1}　 \\
\Longleftrightarrow p(n-k+1) &\ge (1-p)k \\
\Longleftrightarrow p(n+1) \ge k
\end{align}

2つ目の式も同様に変形できる。

<!-- めんどくさかったので丁寧に整形するのはいつか -->

\begin{align}
p_{k+1} = \frac{p}{1-p} \frac{n-k}{k+1} p_{k} &\le p_{k} \\
\Longleftrightarrow p(n-k) &\le (1-p)(k+1) \\
\Longleftrightarrow pn \le k-p+1 \\
\Longleftrightarrow p(n+1) \le k+1 
\end{align}

よって$k$について以下の不等式を解くと確率が最大になる時の$k$がもとまる。

$$
p(n+1)-1 \le k \le p(n+1)
$$

これを満たす整数$k$は$p(n+1)$が整数かどうかで変わる。

$p(n+1)$が整数のとき、$k=p(n+1),p(n+1)-1$である。

$p(n+1)$が整数ではないとき、$k=[p(n+1)]$となる。

:::{.extra-space3}:::

$p(n+1)$が整数の時のグラフ！
```{python}
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import binom
import japanize_matplotlib

# 複数のn, p値を定義
params = [(9, 0.2), (9, 0.5), (19, 0.7), (19, 0.5), (19, 0.7)]

# x の範囲を定義
x = np.arange(0, 21)

# グラフのプロット
plt.figure(figsize=(10, 6))

for n, p in params:
    pmf = binom.pmf(x, n, p)
    plt.plot(x, pmf, marker='o', linestyle='-', label=f'n = {n}, p = {p}')

# x軸の目盛りを整数に設定
plt.xticks(np.arange(0, 21, 1))

plt.xlabel('x')
plt.ylabel('確率')
plt.title('nとpを変動させた二項分布')
plt.legend()
plt.grid(True)
plt.savefig('binom_distribution.png')
plt.show()
```


$p(n+1)$が整数の時のグラフ！
```{python}
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import binom
import japanize_matplotlib

# 複数のn, p値を定義
params = [(10, 0.2), (10, 0.5), (10, 0.7), (20, 0.5), (20, 0.7)]

# x の範囲を定義
x = np.arange(0, 21)

# グラフのプロット
plt.figure(figsize=(10, 6))

for n, p in params:
    pmf = binom.pmf(x, n, p)
    plt.plot(x, pmf, marker='o', linestyle='-', label=f'n = {n}, p = {p}')

# x軸の目盛りを整数に設定
plt.xticks(np.arange(0, 21, 1))

plt.xlabel('x')
plt.ylabel('確率')
plt.title('nとpを変動させた二項分布')
plt.legend()
plt.grid(True)
plt.savefig('binom_distribution.png')
plt.show()
```


グラフで見てみるとわかりやすいですね！

### ⑵

$n=10,k=9$のとき @nte-one　より

$$
p_9=\binom{10}{9} (\frac{1}{2})^{10}
$$

$$
p_{18}=\binom{20}{18} (\frac{1}{2})^{20}
$$

$$
\binom{10}{9}={}_{10} C_9={}_{10} C_1=10,  
\binom{20}{18}={}_{20} C_{18}={}_{20} C_2=190
$$

よって　$p_9=\binom{10}{9} (\frac{1}{2})^{10} > p_{18}=\binom{20}{18} (\frac{1}{2})^{20}$

$p_{9}$の方が確率は大きい。


# 問2

## 問題
ポアソン分布$Po(\lambda)$の確率関数を$p_k=P(X=k)$,$k=0, \ldots,$とする。

⑴$p_k$を$p_{k-1}$を用いて表せ。$\{p_0,\ldots,\}$の中で最大を与える$k$を求めよ

⑵少なくとも１回以上起こる確率が90%以上になる$\lambda$の条件を求めよ

## 解答

### ⑴

問１と同じですね。

::: {#nte-one .callout-note}
確率変数$X$ポアソン分布$Po(\lambda)$に従う時、$X=k$となる確率は下のようになる。

[ここ](/posts/seminor2024_0618/)に詳しく書いてある。


$$
p(k) = P(X=k) = \frac{\lambda^k}{k!}e^{-\lambda}, k = 0,1,2,3, \ldots
$$

:::

$p_k= \frac{\lambda^k}{k!}e^{-\lambda}$ を、$p_{k-1}= \frac{\lambda^{k-1}}{(k-1)!}e^{-\lambda}$ を用いて表す。

$$
p(k) = \frac{\lambda^k}{k!}e^{-\lambda} = \frac{\lambda \lambda^{k-1} }{k(k-1)!}e^{-\lambda} =\frac{\lambda}{k}p_{k-1}
$$

$p_k \ge p_{k-1}$かつ$p_k \ge p_{k+1}$となるような$k$の確率が最大となります。

$$
p_k = \frac{\lambda}{k}p_{k-1} \ge p_{k-1} \Longleftrightarrow \lambda \ge k
$$

$$
p_{k+1} = \frac{\lambda}{k+1}p_{k} \le p_{k} \Longleftrightarrow \lambda \le k+1
$$

よって$\lambda-1 \le k \le \lambda$ となります。

$\lambda$が整数の時、$k=\lambda-1,\lambda$。

$\lambda$が整数ではない時、$k=[\lambda]$となります。

### ⑵
少なくとも１回以上起こる確率は

$$
P(X \le 1)=1-P(X=0)=1-\frac{\lambda^0}{0!}e^{-\lambda}=1-e^{-\lambda} \ge 0.9
$$

$$
e^{-\lambda} \le 0.1
$$

両辺$e$を底数とする対数を取ると、
$$
-\lambda \le \log 0.1 = - \log 10
$$

$$
\lambda \ge \log 10
$$