---
title: "各確率分布の期待値・分散の求め方(制作途中)"
format: html
code-fold: true
date: last-modified
toc: true
toc-location: left
lang: ja
---

# 二項分布

$X \sim Bin(n,p)$ のとき、$E[X]=np$ , $V[X]=np(1-p)$ である。

## $E[X]=np$ の求め方

\begin{align}
E[X] &= \sum_{k=0}^{n} k P(X=k) \\
&= \sum_{k=0}^{n} k 
\begin{pmatrix}
   n \\
   k
\end{pmatrix} p^k (1-p)^{n-k} \\
&= \sum_{k=0}^{n} k \frac{n!}{k!(n-k)!} p^k (1-p)^{n-k} \\
&= \sum_{k=1}^{n} \frac{n!}{(k-1)!(n-k)!} p^k (1-p)^{n-k} \\
&= \sum_{k=1}^{n} \frac{n!(n-k+1)}{(k-1)!(n-(k-1))!} p^k (1-p)^{n-k} \\
&= \sum_{k'=0}^{n-1} \frac{n!(n-k+1)}{(k')!(n-k')!} p^k (1-p)^{n-k} \\


\end{align}


## $V[X]=np(1-p)$ の求め方

同じ求め方で求めれると思われる。

あとはベルヌーイ分布の和の分布でも求めれそう。

確率母関数から求める方法もある。

$G_X(s)=E[s^X]=(ps+1-p)^n$, $M_X(t)=E[e^{tX}]=(pe^t+1-p)^n$ から求める方法もある。

$E[X]=\frac{d}{ds} G_X(s)|_{s=1} = n(ps+1-p)^{n-1} p|_{s=1}=np$

$E[X]=\frac{d}{dt} M_X(t)|_{t=0} = n(pe^t+1-p)^{n-1} p|_{t=0}=np$

$E[X(X-1)]= \frac{d^2}{ds^2} G_X(s)|_{s=1} = \frac{d}{ds} \{n(ps+1-p)^{n-1} p\}|_{s=1}= \{n(n-1)(ps+1-p)^{n-2} p^2\}|_{s=1}=n(n-1)p^2$

$E[X^2]=\frac{d^2}{dt^2} M_X(t)|_{t=0}= \frac{d}{dt}\{n(pe^t+1-p)^{n-1} p\}|_{t=0}=n(n-1)(pe^t+1-p)^{n-2} p^2|_{t=0}=n(n-1)p^2$

$V[X]=E[X^2]-(E[X])^2=n(n-1)p^2-(np)^2????$

$V[X]=E[X^2]-(E[X])^2=E[X(X-1)]+E[X]-(E[X])^2=n(n-1)p^2+np-(np)^2=np(1-p)$


# ベルヌーイ分布



$X \sim Ber(p)$ のとき、$E[X]=p$ , $V[X]=p(1-p)$ である。


# 幾何分布

$X \sim Geo(p)$ のとき、$E[X]=\frac{q}{p}$ , $V[X]=\frac{q}{p^2}$ である。

# ポアソン分布

$X \sim Po(\lambda)$ のとき、$E[X]=\lambda$ , $V[X]=\lambda$ である。

$E[X]=\sum_{k=0}^{\infty}k \frac{\lambda^k}{k!} e^{-\lambda}=\sum_{k=1}^{\infty} \frac{\lambda \lambda^{k-1}}{(k-1)!} e^{-\lambda}=\sum_{k'=0}^{\infty} \frac{\lambda \lambda^{k'}}{(k')!} e^{-\lambda}=\lambda  \sum_{k'=0}^{\infty} \frac{\lambda^{k'}}{(k')!} e^{-\lambda}=\lambda$

$E[X(X-1)]=\sum_{k=0}^{\infty}k(k-1) \frac{\lambda^k}{k!} e^{-\lambda}=\sum_{k=2}^{\infty} \frac{\lambda^2 \lambda^{k-2}}{(k-2)!} e^{-\lambda}=\sum_{k'=0}^{\infty} \frac{\lambda^2 \lambda^{k'}}{(k')!} e^{-\lambda}=\lambda^2  \sum_{k'=0}^{\infty} \frac{\lambda^{k'}}{(k')!} e^{-\lambda}=\lambda^2$

$V[X]=E[X^2]-\{E[X]\}^2=E[X(X-1)]+E[X]-\{E[X]\}^2= \lambda^2 + \lambda - \lambda^2 =\lambda$

確率母関数、積率母関数からも求めれそうです。

ポアソン分布の確率母関数$G_X(s)=\exp\{s\lambda-\lambda\}$,積率母関数は$M_X(t)=\exp\{e^t\lambda-\lambda\}$である。

$E[X]=\frac{d}{ds}G_X(s)|_{s=1}= \{\lambda \exp\{s\lambda-\lambda\}\}|_{s=1} = \lambda$

$E[X]=\frac{d}{dt}M_X(t)|_{t=0}= e^t\lambda \exp\{e^t\lambda-\lambda\}|_{t=0} = \lambda$

$E[X(X-1)]=\frac{d^2}{ds^2}G_X(s)|_{s=1}= \frac{d}{ds}\{\lambda \exp\{s\lambda-\lambda\}\}|_{s=1} =\{\lambda^2 \exp\{s\lambda-\lambda\}\}|_{s=1} = \lambda^2$

$E[X^2]=\frac{d^2}{dt^2}M_X(t)|_{t=0}= \frac{d}{dt} \{e^t\lambda \exp\{e^t\lambda-\lambda\}\}|_{t=0}$

# 離散一様分布

$f(x)=\frac{1}{N}$ より、$E[X]=\frac{N+1}{2}$、$V[X]=\frac{N^2-1}{12}$

## $E[X]=\frac{N+1}{2}$ の求め方

$$
E[X]=\sum_{k=1}^{N} k \frac{1}{N} = \frac{1}{N} \sum_{k=1}^{N} k =  \frac{1}{N} \frac{N(N+1)}{2} = \frac{N+1}{2}
$$

## $V[X]=\frac{N^2-1}{12}$ の求め方

$$
E[X^2]=\sum_{k=1}^{N} k^2 \frac{1}{N} = \frac{1}{N} \sum_{k=1}^{N} k^2 =  \frac{1}{N} \frac{N(N+1)(2N+1)}{6} = \frac{(N+1)(2N+1)}{6}
$$

$$
V[X]=E[X^2]-(E[X])^2 = \frac{(N+1)(2N+1)}{6} - \frac{(N+1)^2}{4} =\frac{4N+2-3N-3}{12} = \frac{(N+1)(N-1)}{12}
$$

# ガンマ分布

$X \sim Ga(\alpha, \beta)$ のとき、$E[X]=\alpha\beta$, $V[X]=\alpha\beta^2$

## $E[X]=\alpha\beta$ の求め方

\begin{align}
E[X]&=\int_{0}^{\infty} x \frac{x^{\alpha-1}e^{-\frac{x}{\beta}}}{\Gamma(\alpha)\beta^{\alpha}} dx \\
&=\int_{0}^{\infty} \frac{x^{(\alpha+1)-1}e^{-\frac{x}{\beta}}}{\Gamma(\alpha)\beta^{\alpha}} dx \\
&=\int_{0}^{\infty} \frac{x^{(\alpha+1)-1}e^{-\frac{x}{\beta}}}{\frac{1}{\alpha}\Gamma(\alpha+1)\frac{1}{\beta}\beta^{\alpha+1}} dx \\
&= \alpha\beta
\end{align}

## $V[X]=\alpha\beta^2$ の求め方

\begin{align}
E[X^2]&=\int_{0}^{\infty} x^2 \frac{x^{\alpha-1}e^{-\frac{x}{\beta}}}{\Gamma(\alpha)\beta^{\alpha}} dx \\
&=\int_{0}^{\infty} \frac{x^{(\alpha+2)-1}e^{-\frac{x}{\beta}}}{\Gamma(\alpha)\beta^{\alpha}} dx \\
&=\int_{0}^{\infty} \frac{x^{(\alpha+2)-1}e^{-\frac{x}{\beta}}}{\frac{1}{\alpha(\alpha+1)}\Gamma(\alpha+2)\frac{1}{\beta^2}\beta^{\alpha+2}} dx \\
&= \alpha(\alpha+1)\beta^2
\end{align}

$$
V[X]=E[X^2]-(E[X])^2 = \alpha(\alpha+1)\beta^2 -\alpha^2 \beta^2 = \alpha\beta^2
$$


# ベータ分布

$X \sim B(a,b)$ のとき、$E[X]=\frac{a}{a+b}$、$V[X]=\frac{ab}{(a+b)^2(a+b+1)}$


## $E[X]=\frac{a}{a+b}$ の求め方

\begin{align}
E[X]&=\int_{0}^1 x \frac{x^{a-1}(1-x)^{b-1}}{B(a,b)} dx  \\
&=\int_{0}^1 x \frac{\Gamma(a+b)}{\Gamma(a)\Gamma(b)}x^{a-1}(1-x)^{b-1} dx \\
&=\int_{0}^1  \frac{\Gamma(a+b)}{\Gamma(a+1+b)}\frac{\Gamma(a+1)}{\Gamma(a)}\frac{\Gamma(a+1+b)}{\Gamma(a+1)\Gamma(b)}x^{a+1-1}(1-x)^{b-1} dx \\
&=\frac{\Gamma(a+b)}{(a+b)\Gamma(a+b)}\frac{a\Gamma(a)}{\Gamma(a)} \int_{0}^1  \frac{\Gamma(a+1+b)}{\Gamma(a+1)\Gamma(b)}x^{a+1-1}(1-x)^{b-1} dx \\
&= \frac{a}{a+b}
\end{align}

## $V[X]=\frac{ab}{(a+b)^2(a+b+1)}$ の求め方

\begin{align}
E[X^2]&=\int_{0}^1 x^2 \frac{x^{a-1}(1-x)^{b-1}}{B(a,b)} dx  \\
&=\int_{0}^1 x^2 \frac{\Gamma(a+b)}{\Gamma(a)\Gamma(b)}x^{a-1}(1-x)^{b-1} dx \\
&=\int_{0}^1  \frac{\Gamma(a+b)}{\Gamma(a+2+b)}\frac{\Gamma(a+2)}{\Gamma(a)}\frac{\Gamma(a+2+b)}{\Gamma(a+2)\Gamma(b)}x^{a+2-1}(1-x)^{b-1} dx \\
&=\frac{\Gamma(a+b)}{(a+b+1)(a+b)\Gamma(a+b)}\frac{a(a+1)\Gamma(a)}{\Gamma(a)} \int_{0}^1  \frac{\Gamma(a+1+b)}{\Gamma(a+1)\Gamma(b)}x^{a+1-1}(1-x)^{b-1} dx \\
&= \frac{a(a+1)}{(a+b+1)(a+b)}
\end{align}

$$
V[X]=E[X^2]-(E[X])^2 =\frac{a(a+1)}{(a+b+1)(a+b)} -\frac{a^2}{(a+b)^2} = \frac{a(a+1)(a+b)-a^2(a+b+1)}{(a+b+1)(a+b)^2} = \frac{ab}{(a+b)^2(a+b+1)}
$$

# 標準正規分布
$X \sim N(0, 1)$ のとき$E[X]=0$,$V[X]=1$ である。

# 正規分布

$X \sim N(\mu, \sigma^2)$ のとき$E[X]=\mu$,$V[X]=\sigma^2$ である。

## $E[X]=\mu$ の求め方

\begin{align}
E[X] = \int^{\infty}_{-\infty} x \frac{1}{\sqrt{2 \pi \sigma^2}} \exp{(\frac{-(x-\mu)^2}{2 \sigma^2})}
\end{align}

標準正規分布から変換する方法も簡単そう。

# 指数分布
$X \sim Ex(\lambda)$のとき$E[X]=\frac{1}{\lambda}$,$V[X]=\frac{1}{\lambda^2}$ である。