---
title: "6月25日「データ解析のための数理統計入門」第2章 2.3 確率変数の変数変換"
format: html
code-fold: true
date: 2024/06/25
toc: true
lang: ja
categories:
  - ゼミ
  - 統計
  - データ解析のための数理統計入門
status: "完了"
---

## 確率変数の変数変換の大まかな説明

<div class="extra-space2"></div>

連続確率変数$X$が与えられた時,$Y=g(X)$となる確率変数$Y$の確率密度関数や累積分布関数を求めることができる!

例：$Y=2X+4$の確率密度関数や累積分布関数を,$X$の確率密度関数$f(x)$や累積分布関数$F(x)$から求める.

## $Y=aX+b$の場合の変数変換

<div class="extra-space2"></div>

$X$の確率密度関数を$f_X(x)$,累積分布関数を$F_X(x)$ で表す。
また,$Y=g(X)$ とおき,$Y$の確率密度関数を$f_Y(y)$,累積分布関数を$F_Y(y)$ で表す。

<div class="extra-space2"></div>

実数$a,b$に対して$Y=aX+b$ となる変換を考える。

<div class="extra-space2"></div>

(後でaで割る時に、aが正か負かで不等式の符号が変わるので、先に場合わけしておく)

$a > 0$のとき
\begin{align*}
  F_Y(y)&=P(Y \leq y) = P(aX+b \leq y) = P(X \leq \frac{y-b}{a}) = F_X(\frac{y-b}{a}) \\
  f_Y(y)&= \frac{d}{dy} F_X (\frac{y-b}{a}) = \frac{1}{a}f_X(\frac{y-b}{a})
\end{align*}

$a < 0$のとき
\begin{align*}
  F_Y(y)&=P(Y \leq y) = P(aX+b \leq y) = P(X \geq \frac{y-b}{a}) =   1-F_X(\frac{y-b}{a}) \\
  f_Y(y)&= -\frac{d}{dy} F_X (\frac{y-b}{a}) = -\frac{1}{a}f_X(\frac{y-b}{a})
\end{align*}

<div class="extra-space2"></div>

よって,全ての実数$a$に対して次の式が成り立つ。

$$
  \mathbf{f_Y(y) = \frac{1}{|a|} f_X(\frac{y-b}{a})}
$$ {#eq-black-uu}

<div class="extra-space3"></div>

## $Y=aX+b$の場合の変数変換と正規分布・標準正規分布

**正規分布**

$X \sim \mathcal{N}(\mu, \sigma^2)$とする.

\begin{equation*}
  f_X(x)= \frac{1}{\sqrt{2\pi}\sigma} \exp\lbrace{-\frac{(x-\mu)^2}{2\sigma^2}}\rbrace
\end{equation*}

<div class="extra-space3"></div>

**正規分布を位置尺度変換する**

$Y=aX+b$ の確率密度関数は @eq-black-uu より

\begin{equation*}
  f_Y(y)= \frac{1}{\sqrt{2\pi}|a|\sigma} \exp\lbrace{-\frac{(y-b-a\mu)^2}{\color{red}
2\color{black}a^2\sigma^2}}\rbrace
\end{equation*}

と書ける.

<div class="extra-space3"></div>

次の命題が成り立つ.


**命題2.1.5** $X \sim \mathcal{N}(\mu, \sigma^2)$とする.$Y=aX+b$とおくと,$Y \sim \mathcal{N}(a\mu+b, a^2\sigma^2)$ となる.また,$Z=(X-\mu)/\sigma$ とおくと $Z \sim \mathcal{N}(0, 1)$ となる。

<div class="extra-space2"></div>

**命題2.1.5を用いて正規分布における確率を求める方法**

$X$が正規分布$\mathcal{N}(\mu, \sigma^2)$に従うとき,実数$x_1,x_2(x_1 < x_2)$ に対する確率$P(x_1<X<x_2)$ を以下のように求める.

\begin{align*}
  P(x_1 < X < x_2) &= P(\frac{x_1 - \mu}{\sigma} < Z < \frac{x_2 - \mu}{\sigma} ) \\
  &= P(Z<\frac{x_2-\mu}{\sigma}) - P(Z<\frac{x_1-\mu}{\sigma}) \\
  &= \Phi(Z<\frac{x_2-\mu}{\sigma})-\Phi(Z<\frac{x_1-\mu}{\sigma})
\end{align*}

正規分布を標準正規分布に標準化することで,確率を求めることができる!

(p55の標準化につながる.)

<div class="extra-space3"></div>

**命題2.1.6** $X$を確率密度関数$f_X(x)$をもつ連続確率変数とし,$g(x)$を,$f_X(x)\neq0$になる$x$の範囲で単調増加もしくは単調減少する関数とする.$Y=g(X)$とおくとき,$Y$の確率密度関数は,

$$
  f_Y(y)=f_X(g^{-1}(y))|\frac{d}{dy}g^{-1}(y)|
$$ {#eq-black-scholes}

ここで,$g^{-1}(y)$は$y=g(x)$の逆関数であり,

$$
  \frac{d}{dy}g^{-1}(y) = \frac{1}{g'(g^{-1}(y))}
$$ {#eq-black-ss}

という等式が成り立つ.

$g(x)$が単調増加関数であるとすると,1対1関数になるので逆関数$g^{-1}(y)$がとれる.

\vspace{2mm}

$g(x)$ が単調増加の場合
\begin{equation*}
F_Y(y)=P(Y \leq y) = P(g(X) \leq y) = P(X \leq g^{-1}(y)) =F_X(g^{-1}(y))
\end{equation*}

\begin{align*}
  f_Y(y)&=\frac{d}{dy}F_Y(y) = \frac{d}{dy}F_X(g^{-1}(y)) = \frac{d}{dx}F_X(x)|_{x=g^{-1}(y)}\frac{d}{dy}g^{-1}(y) \\
  &=f_X(g^{-1}(y)) \frac{d}{dy}g^{-1}(y)
\end{align*}

$g(x)$ が単調減少の場合

\begin{align*}
 F_Y(y)&=  P(g{X} \leq y) = P(X \geq g^{-1}(y)) =1-F_X(g^{-1}(y)) \\
 f_Y(y)&=-f_X(g^{-1}(y)) \frac{d}{dy}g^{-1}(y)=f_X(g^{-1}(y)) |\frac{d}{dy}g^{-1}(y)|
\end{align*}

単調減少の時,$g^{-1}(x)$は負になるので、絶対値を取ると一般化できる。

よって、@eq-black-scholes が成り立つ。

@eq-black-ss について,

\begin{align*} 
  y=g(x) \\
  1 = g'(x)(dx/dy)
\end{align*}

$x=g^{-1}(y)$を代入する.
\begin{equation*}
  1 = g'(g^{-1}(y))\frac{d}{dy} g^{-1}(y)
\end{equation*} 
  
@eq-black-ss が成り立つので,逆関数の微分の計算が可能になる.


